# Default values for face-recognition
replicaCount: 3

image:
  repository: face-recognition
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8000"
  prometheus.io/path: "/metrics"

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
  hosts:
    - host: face-api.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: face-recognition-tls
      hosts:
        - face-api.example.com

resources:
  limits:
    cpu: 2000m
    memory: 4Gi
    nvidia.com/gpu: 1
  requests:
    cpu: 1000m
    memory: 2Gi
    nvidia.com/gpu: 1

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector:
  nvidia.com/gpu: "true"

tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: face-recognition
          topologyKey: kubernetes.io/hostname

persistence:
  enabled: true
  storageClass: fast-ssd
  accessMode: ReadWriteMany
  size: 100Gi
  mountPath: /app/data

config:
  logLevel: INFO
  faceModel: buffalo_l
  detectorBackend: scrfd
  device: cuda
  indexType: ivfpq
  similarityThreshold: 0.65
  topK: 5
  rateLimitEnabled: true
  rateLimitRequests: 100
  rateLimitWindow: 60

secrets:
  databaseUrl: ""
  apiKey: ""

postgresql:
  enabled: true
  auth:
    username: facedb
    password: changeme
    database: facedb
  primary:
    persistence:
      enabled: true
      size: 50Gi

redis:
  enabled: false
  auth:
    enabled: true
    password: changeme
  master:
    persistence:
      enabled: true
      size: 10Gi

monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s